name: gestiona_app
description: "App de gestión de piscinas y socorristas para ayuntamientos y empresas."
publish_to: 'none'
version: 2.2.0+14

environment:
  sdk: ^3.8.0

dependencies:
  auto_size_text: ^3.0.0
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.8.0
  get: ^4.7.2
  get_storage: ^2.1.1
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  table_calendar: ^3.2.0
  flutter_launcher_icons: ^0.14.3
  package_info_plus: ^8.3.0
  version: ^3.0.2
  url_launcher: ^6.3.1
  firebase_core: ^3.15.1
  firebase_messaging: ^15.2.9
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo-app.png
    - assets/GESTIONA-LOGO.png
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
          weight: 500
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
          weight: 700

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/logo-app.png'
